server:
    port: 8001
spring:
    application:
        name: etlservice
    datasource:
        url: 'jdbc:postgresql://noteappdb.ct6dtngodqi6.us-east-2.rds.amazonaws.com:5432/noteappdb'
        username: 'postgres'
        password: 'password'
        platform: POSTGRESQL
        testWhileIdle: true
        validationQuery: 'SELECT 1'
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        database: postgresql
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            
file:
    outpup: notes.json
